#!/usr/bin/env bash

# call this function to write to stderr
echo_stderr ()
{
    echo "$@" >&2
}

action="$1"

SOURCE="${BASH_SOURCE[0]}"
SOURCE=$(readlink -f "$SOURCE")
SOURCE_DIR=$(dirname "$SOURCE")

case $action in
    save )
        $SOURCE_DIR/git_recursive_stash_save
        ;;
    apply )
        $SOURCE_DIR/git_recursive_stash_apply
        ;;
    pop )
        $SOURCE_DIR/git_recursive_stash_apply &&
            $SOURCE_DIR/git_recursive_stash_delete
        ;;
    *)
        echo_stderr "Invalid command: expected one of save, apply or pop"
        exit 1
        ;;
esac
