#!/usr/bin/env bash

# call this function to write to stderr
echo_stderr ()
{
    echo "$@" >&2
}

if (git rev-parse --is-inside-work-tree 2> /dev/null 1>&2); then
	:
else
    err_code=$?
    echo_stderr "Not inside git repository"
    exit $err_code
fi

if [[ "$1" != '-f' && "$1" != '--force' ]]; then
	echo_stderr "If -f or --force is not specified nothing will be done"
	exit
else
	git reset --hard &&
	git submodule foreach --recursive git reset --hard &&
	git submodule update --recursive --init
fi
