#!/usr/bin/env bash

# call this function to write to stderr
echo_stderr ()
{
    echo "$@" >&2
}

function check_dir_valid() {
    inputdir="$1"
    if [[ -z "$inputdir" ]]; then
        echo_stderr "inputdir is empty, illegal"
        exit 1  # exit script, something went wrong
    fi

    pushd "$inputdir" > /dev/null &&
        inputdir="$PWD" &&
    popd > /dev/null
    err_code=$?
    if [[ $err_code -ne 0 ]]; then
        echo_stderr "'$inputdir' does not appear to be a valid directory"
        exit $err_code
    else
        echo -n "$inputdir"
    fi
}

function join_by { local IFS="$1"; shift; echo "$*"; }

function clean_up_repo() {
    if [[ -z "$1" ]]; then
        echo_stderr "source_repo_root is empty, illegal"
        exit 1  # exit script, something went wrong
    fi
    pushd "$1" > /dev/null &&
        git reset --hard &&
        git submodule foreach --recursive git reset --hard &&
        git submodule update --recursive --init
    popd > /dev/null
}

sim_prep_dir_arg="$1"
if [[ -z "$sim_prep_dir_arg" ]]; then
    echo_stderr "Need to specify the sim preparation directory as an argument"
    exit 1
fi
sim_preparation_dir=$(check_dir_valid "$sim_prep_dir_arg")
echo "==================================="$(echo -n "$sim_prep_dir_arg" | sed 's/./=/g')
echo "Performind Simulation in directory $sim_prep_dir_arg"
echo "==================================="$(echo -n "$sim_prep_dir_arg" | sed 's/./=/g')

# relevant directory from which to run the program
sim_working_dir=$(check_dir_valid "$sim_preparation_dir/$(cat $sim_preparation_dir/cwd)")

# validate working directory
pushd $sim_working_dir > /dev/null
    # Check if inside a valid repository
    if (git rev-parse --is-inside-work-tree 2> /dev/null 1>&2); then
        :
    else
        err_code=$?
        echo "The directory from which to run the command is not inside the git repository"
        exit $err_code
    fi

    # get root directory of source repository (it is assumed that the current working directory is inside that)
    source_repo_root="$(git rev-parse --show-toplevel)"
popd >/dev/null


# Verify the validity of the repository in source_repo_root
pushd $source_repo_root >/dev/null
    if [[ $(git status --porcelain | wc -l) -ne 0 ]]; then
        echo_stderr "There appear to be untracked/uncommitted files in \"$source_repo_root\". Will not continue checkout"
        exit 1
    fi
popd >/dev/null

# Apply patches to source directory as necessary
pushd $source_repo_root > /dev/null &&
    # Checkout and run relevant simulation
    checkoutsim.sh $sim_preparation_dir
    err_code=$?
    if [[ $err_code -ne 0 ]]; then
        echo_stderr "The checkout of the simulation did not work out"

        # This is safe because the repository was verified to be clean before running checkoutsim.sh
        clean_up_repo .
        exit $err_code
    fi
popd >/dev/null

pushd $sim_working_dir > /dev/null &&
    mapfile -t command_array < "$sim_preparation_dir/command" &&
    (echo "Running The following command:";
     echo "=============================================================";
     echo "${command_array[@]}";
     echo "=============================================================") &&

    "${command_array[@]}"

    err_code=$?
    if [[ $err_code -ne 0 ]]; then
        echo_stderr "The simulation exited with some error"
    else
        echo "completed simulation $sim_prep_dir_arg"
    fi
    clean_up_repo .
    exit $err_code
popd > /dev/null

