#!/usr/bin/env bash

# call this function to write to stderr
echo_stderr ()
{
    echo "$@" >&2
}

function join_by { local IFS="$1"; shift; echo "$*"; }

# Ask for simulation name if not specified
if [[ "$1" != "-n" ]]; then
    pack_args=()
else
    shift
    sim_name="$1"
    shift
    pack_args=("-n" "$sim_name")
fi


SOURCE="${BASH_SOURCE[0]}"
SOURCE=$(readlink -f "$SOURCE")
SOURCE_DIR=$(dirname "$SOURCE")

simdir=$($SOURCE_DIR/pack_sim_dir "${pack_args[@]}")

err_code=$?
if [[ $err_code -ne 0 ]]; then
    echo_stderr "Failed to create the simulation directory :("
    exit $err_code
fi

pushd "$simdir" > /dev/null &&
    join_by $'\n' "$@" > command &&
popd > /dev/null
